name: docs
run-name: ${{ github.actor }} is building a new image

on:
  push:
    branches:
    - main
    paths:
    - docker/**
    - src/**
    - tests/**
    - pyproject.yml
  pull_request:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Authenticate with the remote Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the image and run the checks
      run: |
        # Determine the version of the image.
        version=$(poetry version -n --no-ansi -s)

        # Validation and test stage
        docker build . -f docker/Dockerfile --target=validate

        # Production stage
        docker build . -f docker/Dockerfile --target=production --tag ${{ vars.DOCKER_REGISTRY }}/peinser/pyconiq:$version